const KEY="financeiro_v1";let transactions=JSON.parse(localStorage.getItem(KEY)||"[]");let chart=null;
const $=id=>document.getElementById(id);
const money=v=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0);
const today=()=>{let d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)};
$("referenceDate").value=today();$("date").value=today();$("todayLabel").textContent=new Date().toLocaleDateString("pt-BR",{weekday:"long",day:"2-digit",month:"long",year:"numeric"});
function save(){localStorage.setItem(KEY,JSON.stringify(transactions));render()}
function range(){let ref=new Date($("referenceDate").value+"T12:00:00"),p=$("periodFilter").value;let s,e;
 if(p==="day"){s=e=new Date(ref)}
 else if(p==="week"){let day=ref.getDay()||7;s=new Date(ref);s.setDate(ref.getDate()-day+1);e=new Date(s);e.setDate(s.getDate()+6)}
 else if(p==="month"){s=new Date(ref.getFullYear(),ref.getMonth(),1);e=new Date(ref.getFullYear(),ref.getMonth()+1,0)}
 else{s=new Date(2000,0,1);e=new Date(2100,0,1)}
 return {s,e}}
function inRange(t,r){let d=new Date(t.date+"T12:00:00");return d>=r.s&&d<=r.e}
function render(){renderDash();renderTable()}
function renderDash(){let r=range(),arr=transactions.filter(t=>inRange(t,r)),inc=arr.filter(t=>t.type==="income"),exp=arr.filter(t=>t.type==="expense");let ti=inc.reduce((a,t)=>a+t.amount,0),te=exp.reduce((a,t)=>a+t.amount,0),pending=exp.filter(t=>t.status==="pending").reduce((a,t)=>a+t.amount,0);
 $("totalIncome").textContent=money(ti);$("totalExpense").textContent=money(te);$("balance").textContent=money(ti-te);$("pending").textContent=money(pending);$("incomeCount").textContent=inc.length+" lançamento(s)";$("expenseCount").textContent=exp.length+" lançamento(s)";
 $("periodText").textContent=$("periodFilter").selectedOptions[0].text;
 let cat={};arr.forEach(t=>cat[t.category||"Sem categoria"]=(cat[t.category||"Sem categoria"]||0)+(t.type==="income"?t.amount:-t.amount));
 $("summaryList").innerHTML=Object.entries(cat).sort((a,b)=>Math.abs(b[1])-Math.abs(a[1])).slice(0,8).map(([k,v])=>`<div class="summary-row"><b>${esc(k)}</b><span class="${v>=0?"green":"red"}">${money(v)}</span></div>`).join("")||"<p>Sem lançamentos no período.</p>";
 let upcoming=transactions.filter(t=>t.type==="expense"&&t.status==="pending").sort((a,b)=>(a.dueDate||a.date).localeCompare(b.dueDate||b.date)).slice(0,8);
 $("upcomingList").innerHTML=table(upcoming,true);
 drawChart(arr,r)}
function drawChart(arr,r){let labels=[],valsI=[],valsE=[];let start=new Date(r.s),end=new Date(r.e),days=Math.round((end-start)/86400000)+1;let step=$("periodFilter").value==="month"&&days>20?1:1;
 for(let i=0;i<days;i+=step){let d=new Date(start);d.setDate(start.getDate()+i);let key=d.toISOString().slice(0,10);labels.push(d.toLocaleDateString("pt-BR",{day:"2-digit",month:"2-digit"}));valsI.push(arr.filter(t=>t.date===key&&t.type==="income").reduce((a,t)=>a+t.amount,0));valsE.push(arr.filter(t=>t.date===key&&t.type==="expense").reduce((a,t)=>a+t.amount,0))}
 if(chart)chart.destroy();let c=$("financeChart").getContext("2d");chart=new Chart(c,{type:"bar",data:{labels,datasets:[{label:"Receitas",data:valsI},{label:"Despesas",data:valsE}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:"bottom"}},scales:{y:{beginAtZero:true,ticks:{callback:v=>"R$ "+Number(v).toLocaleString("pt-BR")}}}}})}
function table(arr,compact=false){if(!arr.length)return '<div style="padding:20px;color:#8993a5">Nenhum lançamento encontrado.</div>';return `<table class="data-table"><thead><tr><th>Data</th><th>Descrição</th><th>Tipo</th><th>Categoria</th><th>Valor</th><th>Status</th>${compact?"":"<th>Ações</th>"}</tr></thead><tbody>${arr.map(t=>`<tr><td>${br(t.date)}</td><td><b>${esc(t.description)}</b><br><small>${esc(t.method||"")}</small></td><td><span class="badge ${t.type}">${t.type==="income"?"Receita":"Despesa"}</span></td><td>${esc(t.category||"-")}</td><td class="${t.type==="income"?"green":"red"}">${money(t.amount)}</td><td><span class="badge ${t.status}">${t.status==="paid"?"Pago/Recebido":"Pendente"}</span></td>${compact?"":"<td><div class='actions'><button class='icon-btn' onclick='editTx("${t.id}")'>✏️</button><button class='icon-btn' onclick='deleteTx("${t.id}")'>🗑️</button></div></td>"}</tr>`).join("")}</tbody></table>`}
function renderTable(){let q=$("searchInput").value.toLowerCase(),tf=$("typeFilter").value,sf=$("statusFilter").value;let arr=transactions.filter(t=>(tf==="all"||t.type===tf)&&(sf==="all"||t.status===sf)&&[t.description,t.category,t.method,t.note].join(" ").toLowerCase().includes(q)).sort((a,b)=>b.date.localeCompare(a.date));$("transactionsTable").innerHTML=table(arr)}
function br(x){return x?new Date(x+"T12:00:00").toLocaleDateString("pt-BR"):"-"}function esc(x){return String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function openModal(t=null){$("modal").classList.remove("hidden");$("modalTitle").textContent=t?"Editar lançamento":"Novo lançamento";$("editId").value=t?.id||"";$("description").value=t?.description||"";$("amount").value=t?.amount??"";$("date").value=t?.date||today();$("dueDate").value=t?.dueDate||"";$("category").value=t?.category||"";$("method").value=t?.method||"";$("status").value=t?.status||"paid";$("note").value=t?.note||"";document.querySelector(`input[name="type"][value="${t?.type||"income"}"]`).checked=true}
function closeModal(){$("modal").classList.add("hidden")}
$("addBtn").onclick=()=>openModal();$("closeModal").onclick=closeModal;$("cancelBtn").onclick=closeModal;$("openAll").onclick=()=>document.querySelector('[data-view="lancamentos"]').click();
$("transactionForm").onsubmit=e=>{e.preventDefault();let id=$("editId").value||crypto.randomUUID();let t={id,type:document.querySelector('input[name="type"]:checked').value,description:$("description").value,amount:Number($("amount").value),date:$("date").value,dueDate:$("dueDate").value,category:$("category").value,method:$("method").value,status:$("status").value,note:$("note").value};let i=transactions.findIndex(x=>x.id===id);if(i>=0)transactions[i]=t;else transactions.push(t);save();closeModal()};
window.editTx=id=>openModal(transactions.find(t=>t.id===id));window.deleteTx=id=>{if(confirm("Excluir este lançamento?")){transactions=transactions.filter(t=>t.id!==id);save()}};
document.querySelectorAll(".nav-btn").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav-btn").forEach(x=>x.classList.remove("active"));b.classList.add("active");let v=b.dataset.view;$("dashboardView").classList.toggle("hidden",v!=="dashboard");$("lancamentosView").classList.toggle("hidden",v!=="lancamentos");$("pageTitle").textContent=v==="dashboard"?"Dashboard":"Lançamentos"});
["periodFilter","referenceDate","searchInput","typeFilter","statusFilter"].forEach(id=>$(id).addEventListener("input",render));
$("exportBtn").onclick=()=>{let blob=new Blob([JSON.stringify(transactions,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="financeiro-backup.json";a.click()};
$("importFile").onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(Array.isArray(x)){transactions=x;save();alert("Dados importados com sucesso!")}}catch{alert("Arquivo inválido.")}};r.readAsText(f)};
$("clearBtn").onclick=()=>{if(confirm("Apagar TODOS os lançamentos? Esta ação não pode ser desfeita.")){transactions=[];save()}};
const chartScript=document.createElement("script");chartScript.src="https://cdn.jsdelivr.net/npm/chart.js";chartScript.onload=render;document.head.appendChild(chartScript);